### ISSUE TITLE
GRUB

### ISSUE THREAD

**Issue by daniyalw** [ToastBreadMan/Os_Project#1]
Would it be ok if I contributed to your OS, but used GRUB for the bootloader instead?

**Comment by julySteuer** [comment]
Yeah sure I have no idea how to use grub but I am currently having to work on another project.
If you know how to make something like this sure (bcs I have minimal knowledge of os programming at this point)
Edit: Could u just fort the repo?

**Comment by daniyalw** [comment]
Yeah, and I will do a pull request.
